kytos/python-openflow

- pyof/v0x01/foundation/base.py
Error with MetaClass and __ordered__ while dealing with rewritten methods.
Now we check if an attribute is not a function before adding it to the
__ordered__ class attribute.
> [v0x01] FIX #24 - Error with MetaClass and __ordered__

- pyof/v0x01/foundation/base.py
- pyof/v0x01/foundation/basic_types.py
I've done improvments on __str__ and __repr__ methods on our bases/basic_types.
Now the "str" method prints the attributes of the message with the respective value of each one, and the "repr" method prints a reference to how someone could instantiate an object just like the required one.
> Improved str and repr on GenericStruct

- pyof/v0x01/common/action.py
- pyof/v0x01/common/flow_match.py
- pyof/v0x01/common/phy_port.py
- pyof/v0x01/controller2switch/port_mod.py
- pyof/v0x01/foundation/base.py
- pyof/v0x01/foundation/basic_types.py
- pyof/v0x01/foundation/exceptions.py
- pyof/v0x01/symmetric/echo_reply.py
- tests/v0x01/test_common/test_action.py
- tests/v0x01/test_common/test_phy_port.py
- tests/v0x01/test_controller2switch/test_port_mod.py
- tests/v0x01/test_foundation/test_basic_types.py
The messages now convert the type during the pack operation.
#changelog: Refactor in order to accept python basic types as messages attributes.
> Refactor in order to accept python basic types as messages attributes.

- pyof/__init__.py
- pyof/v0x01/asynchronous/error_msg.py
- pyof/v0x01/asynchronous/flow_removed.py
- pyof/v0x01/common/action.py
- pyof/v0x01/common/phy_port.py
- pyof/v0x01/common/queue.py
- pyof/v0x01/controller2switch/flow_mod.py
Fix #41. There's only one error because v0x02 code is broken. Devs should check doc output before commit. There are still many comments to be rewritten using Sphinx style. For me, enum name has white font color in a white background, so maybe we should change the doc's theme.
> Remove warnings and errors of doc build

- pyof/v0x01/controller2switch/features_reply.py
- pyof/v0x01/controller2switch/get_config_reply.py
- pyof/v0x01/controller2switch/set_config.py
- pyof/v0x01/foundation/base.py
- pyof/v0x01/foundation/basic_types.py
- pyof/v0x01/foundation/exceptions.py
There were some bugs like a misspelled class name that we can avoid by integrating pylint in the editor.
Pylint doesn't recognize members from metaclasses, but we shouldn't ignore these warnings in the whole project. Therefore, I used code comments to ignore missing `__ordered__` member.
> Issue #78 pylint

- tests/test_struct.py
Now, if the raw dump file does not exist, the test does not fail.
Instead of failing, the tests that require the file are skipped and a log message is printed to
inform that a raw dump file need to be generated/added.
> Improving TestStruct helper class.

- pyof/foundation/base.py
This error could not be noticed because of #169 (tests pass if a doctest fails).
> Fix doctest import error

- docs/Makefile
Just a small improvement. Now, while using 'livehtml' or using the default docs build, our docs will have links without the ".html" end.
> [docs] Improve livehtml to use dirhtml instead of html sphinx build

- pyof/v0x04/common/utils.py
> Add unpack_message method to v0x04

- pyof/v0x02/__init__.py
- pyof/v0x02/common/__init__.py
- pyof/v0x04/common/port.py
- setup.py
It is not implemented. There were only 2 `__init__.py` files.
> Remove v0x02

- CHANGELOG.rst
- pyof/foundation/basic_types.py
- tests/test_foundation/test_basic_types.py
- tests/v0x01/test_asynchronous/test_error_msg.py
Before, packed BinaryData would be empty if given a non-byte value.
E.g.: ``BinaryData('string').pack() == b''``. Now, we raise ``ValueError`` to prevent the user from losing data.
> BinaryData: raise instead of discarding data

- requirements-dev.txt
- tox.ini
After last Pylama release, we have new linter warnings to be fixed in
a later version.
> [minor] Downgrade pylama

- pyof/v0x04/controller2switch/multipart_reply.py
Fix #463
Remove an unnecessary enum_ref, return the correct type for list bodies.
> Fix MultipartReply unpacking

- pyof/v0x04/asynchronous/packet_in.py
- pyof/v0x04/common/flow_match.py
Improve PacketIn and Match classes by adding helper methods to access OXM_TLV
values. Fix #465
> [v0x04] Improve PacketIn and Match classes.

- CHANGELOG.rst
- pyof/v0x04/common/flow_instructions.py
Fix #458
Optionally, the `update_length` method can be called on `__init__` AND when packing, but this is not the lib's default behavior.
> Make instructions update the length when packing

- CHANGELOG.rst
- pyof/foundation/base.py
- pyof/foundation/exceptions.py
Currently, the user doesn't know the name of attribute containing the wrong value:
```python
from pyof.v0x04.controller2switch.flow_mod import FlowMod
FlowMod().pack()
```
> Add attribute name to PackException message

- pyof/utils.py
- pyof/v0x01/common/utils.py
- pyof/v0x04/common/utils.py
Reuse the methods unpack_message from pyof.[version].common.utils
Create a constant called MESSAGE_TYPES
Fix kytos/python-openflow#344
> Improve unpack method in pyof/utils

- pyof/v0x01/controller2switch/get_config_reply.py
OFPT_GET_CONFIG_REPLY messages have the wrong message_type where instead of receiving Type.OFPT_GET_CONFIG_REPLY it was getting Type.OFPT_SET_CONFIG.
> Fixing OFPT_GET_CONFIG_REPLY message type

- pyof/v0x04/asynchronous/error_msg.py
This PR adds support for proper handling of OFP_ERROR messages, without this, any OpenFlow1.3 OFP_ERROR messages resulted in restarting the OpenFlow connection with the switches (this was impacting the deployment at ESnet):
Example: (this is when I flow that I was pushing resulted in OFP_ERROR) 
```
2018-10-21 13:07:50,793 - DEBUG [controller:controller.py:387] (MainThread) looking for listeners for kytos/core.openflow.raw.in
2018-10-21 13:07:50,794 - DEBUG [controller:controller.py:410] (MainThread) Raw Event handler called
2018-10-21 13:07:50,794 - DEBUG [kytos/of_core:main.py:200] (Thread-79) Connection ('ESnet_switch', 47144): New Raw Openflow packet - 0401004cc4d8070000040007040e0078c4d80700000000000000000000000000000000
000000000000000fa0ffffffffffffffffffffffff0001000000010012800000 …
```
> Added support for OpenFlow 1.3 OFP_ERROR codes with the get_class method

- setup.cfg
- setup.py
- tests/test_struct.py
- tests/v0x04/test_struct.py
The output is a little different - it counts `skipped` and `expected failures` as `passed`, but it seems OK.
unittest:
```
Pack, unpack the result and assert the values are equal. ... ok
test_max_field_value (tests.v0x04.test_common.test_flow_match.TestOxmTLV)
Use all bits of oxm_field. ... ok
test_pack_invalid_field (tests.v0x04.test_common.test_flow_match.TestOxmTLV)
Raise PackException if field is invalid for a class. ... ok
test_pack_overflowed_field (tests.v0x04.test_common.test_flow_match.TestOxmTLV)
Raise PackException if field is bigger than 7 bit. ... ok
test_unpack_invalid_field (tests.v0x04.test_common.test_flow_match.TestOxmTLV)
Raise UnpackException if field is invalid for a class. ... ok
----------------------------------------------------------------------
Ran 268 tests in …
```
> pytest as the default test tool

- pyof/v0x04/controller2switch/multipart_reply.py
There was an error because "int" doesn't have value attribute
> Fix MultipartReply error when call isinstance method

- pyof/v0x04/controller2switch/common.py
- tests/v0x04/test_controller2switch/test_group_mod.py
Fix the issue #574 about Buckets with list of Actions causing the length to be dynamic.
> Customize unpack to Bucket class to support dynamic length.

- setup.py
Today, the package hosted in PyPI doesn't have a long description,
this commit adds the long_description field by reading the README.rst file.
> Added long description field for display in pypi.org (PyPI)

- pyof/foundation/basic_types.py
Implement the IPv6 address class aiming to be used to implement the IPv6 source and IPv6 destination match fields as proposed in in of_core: https://github.com/kytos/of_core/issues/77
> Add IPv6 address class

- pyof/foundation/network_types.py
- tests/unit/test_foundation/test_network_types.py
Implement the IPv6 packet structure and also the unit test for the IPv6 packet class.
Note: the checks for the pull request failed due to not having the IPv6 address class merged from the #607 pull request yet.
> Add IPv6 packet structure

- README.rst
Solve the problem of broken links to the contribution guide and python-openflow API reference manual.
> Update broken links on README.rst

- README.rst
Users should prefer the `unpack` wrapper from utils over using `unpack_message` directly.
The helper should perform the first validations and then call the underlying `unpack_message` as defined by the version.
> Change unpack example in README

- tests/unit/test_struct.py
- tests/unit/v0x01/test_controller2switch/test_flow_mod.py
- tests/unit/v0x01/test_symmetric/test_vendor_header.py
The Capstone 1 team at FIU attempted to solve easy issue #434  for our Senior Project class. This may not be a probable solution, since it feels like the test results for the 2 skipped tests may be inaccurate; however, we tested it in our environment and it is working in some way.
> Allow minimum-size test to never skip

- Makefile
- README.rst
- setup.py
Related: https://github.com/kytos/kytos/issues/1149
- Remove python 3.6 references
- Added references for python 3.7 and 3.8 in the setup.py file
> Remove python 3.6 references

- pyof/foundation/base.py
Current methods in the class are `is_valid`, `is_bitmask` and... `isenum`.
I've checked all the other projects and the method is only used inside the same file.
> Standardize `isenum` to `is_enum`

- pyof/foundation/base.py
- pyof/foundation/basic_types.py
- pyof/foundation/network_types.py
- tests/unit/test_foundation/test_basic_types.py
The most controversial change is in 8b9240d4f90b759d01cdf987a9cca2351a487ed0. The rest are just improvements in the tests.
This is a basic first step that can make it easier to fix kytos/flow_manager#97 (UBInt serialization error).
> UBInt casting to int() + improved unit tests

- docs/Makefile
- requirements/dev.txt
Working on #595 
By commenting the line 5 of docs Makefile `SPHINXOPTS = -W` you've got those warnings, that leads 
to remove the inheritance of `metaclass=MetaBitMask` from `GenericBitMask`, what reduces significantly 
the amount of warnings. Maybe this could mean that the problem is in the meta class `MetaBitMask`. 
Also changed sphinx version in  `dev.txt`.
> SPHINXOPTS commented and sphinx build upgrade to 3.1.2

- pyof/v0x01/controller2switch/common.py
Fixes #630
The constructor of the class PortStatsRequest accepts a parameter named port_no.
Its default value was None, causing and error when the request was packed.
This PR changes the default value to Port.OFPP_NONE.
All unit tests ran ok.
> Default value for port_no in PortStatsRequest changed

- pyof/foundation/base.py
- pyof/v0x04/common/action.py
- pyof/v0x04/common/header.py
- pyof/v0x04/controller2switch/common.py
- pyof/v0x04/controller2switch/group_mod.py
Fix #635.
Previous `repr()` examples:
```python
gm: GroupMod(xid=UBInt32(4))
gm.buckets[0]: <pyof.v0x04.controller2switch.common.Bucket object at 0x10f062d30>
gm.buckets[0].actions: [
<pyof.v0x04.common.action.ActionSetField object at 0x10f069130>,
<pyof.v0x04.common.action.ActionSetField object at 0x10f069490>,
<pyof.v0x04.common.action.ActionOutput object at 0x10f069790>]
gm.header: <pyof.v0x04.common.header.Header object at 0x10f062be0>
```
With this PR:
```python
gm: GroupMod(xid=4, OFPGC_ADD, group_type=2, group_id=8,
buckets=[
Bucket(actions=[
ActionSetField(OFPXMT_OFB_ETH_SRC, b'\x00\x00\x00\x11\x11T'), 
ActionSetField(OFPXMT_OFB_ETH_DST, b'\x00\x00\x00""T'),
ActionOutput(port=1)])])
gm.header: Header(version=4, xid=4, OFPT_GROUP_MOD)
```
> Add __repr__ to `GroupMod` (+4 other classes)
