pyof/v0x01/foundation/base.py
pyof/v0x01/foundation/exceptions.py

- Creates the "validate" method on GenericStruct
- Creates the "_validate_attributes_type" method
- Call validate on pack
- Creates a new Exception (AttributeTypeError)

FIX #16 and FIX #17

---

tests/v0x01/test_asynchronous/test_packet_in.py
tests/v0x01/test_asynchronous/test_port_status.py
tests/v0x01/test_common/test_phy_port.py

- Packet_In spec size is wrong
- PortStatus and PhyPort were using a problematic constant

[v0x01][Tests] Fixing errors on tests.

---

pyof/v0x01/asynchronous/error_msg.py
pyof/v0x01/asynchronous/packet_in.py
pyof/v0x01/common/phy_port.py
pyof/v0x01/common/queue.py
pyof/v0x01/controller2switch/common.py
pyof/v0x01/controller2switch/features_reply.py
pyof/v0x01/controller2switch/flow_mod.py
pyof/v0x01/controller2switch/flow_stats.py
pyof/v0x01/controller2switch/packet_out.py
pyof/v0x01/controller2switch/queue_get_config_reply.py
pyof/v0x01/controller2switch/set_config.py
pyof/v0x01/controller2switch/stats_reply.py
pyof/v0x01/controller2switch/stats_request.py
pyof/v0x01/foundation/base.py
pyof/v0x01/foundation/basic_types.py
pyof/v0x01/foundation/exceptions.py
tests/v0x01/test_asynchronous/test_error_msg.py
tests/v0x01/test_asynchronous/test_packet_in.py
tests/v0x01/test_common/test_queue.py
tests/v0x01/test_controller2switch/test_flow_mod.py
tests/v0x01/test_controller2switch/test_flow_stats.py
tests/v0x01/test_controller2switch/test_packet_out.py
tests/v0x01/test_symmetric/test_echo_request.py

CHANGELOG: New Basic Types Created (BinaryData and Lists classes)

Fix #13 special lists

---

docs/_static/custom.css
pyof/v0x01/foundation/base.py

#CHANGELOG: Better library documentation.

better documentation

---

CONTRIBUTE.md
HACKING.md
README.md

Markdown docs review

---

pyof/v0x01/common/header.py
pyof/v0x01/common/phy_port.py
pyof/v0x01/controller2switch/flow_mod.py
pyof/v0x01/foundation/base.py
pyof/v0x01/foundation/basic_types.py
pyof/v0x01/foundation/exceptions.py
tests/v0x01/test_common/test_header.py
tests/v0x01/test_controller2switch/test_barrier_reply.py
tests/v0x01/test_controller2switch/test_barrier_request.py
tests/v0x01/test_controller2switch/test_features_reply.py
tests/v0x01/test_controller2switch/test_features_request.py
tests/v0x01/test_controller2switch/test_flow_mod.py
tests/v0x01/test_symmetric/test_echo_reply.py
tests/v0x01/test_symmetric/test_echo_request.py
tests/v0x01/test_symmetric/test_hello.py

FIX #37 
#CHANGELOG: Major refactor on Base and BasicTypes. Removed "Descriptors" behaviour, added GenericBitmask, Added HWAddress basic_class.

Issue #37 descriptors

---

pyof/v0x01/common/phy_port.py
pyof/v0x01/controller2switch/flow_mod.py
pyof/v0x01/foundation/base.py

FIX #48 
CHANGELOG: MetaBitMask improvment for subclasses declaration.

Improved MetaBitMask class so the BitMask classes can behave like enums

---

.coveragerc
HACKING.md

Fix the command to analyze coverage and make it slightly less verbose.

Fix coverage doc

---

pyof/v0x01/controller2switch/features_request.py

As discussed while reviewing README.md

Fix #67: FeatureRequest message type

---

CONTRIBUTE.md

How to add upstream repo, minor doc fixes

---

pyof/v0x01/controller2switch/packet_out.py
pyof/v0x01/foundation/exceptions.py
tests/v0x01/test_controller2switch/test_packet_out.py

Validate packet_out in_port value as in 1.0.1

---

setup.py

#77 - Adds pep8 check on python setup.py test routine

Added pep8 check on python setup.py test

---

tests/v0x01/test_common/test_action.py
tests/v0x01/test_common/test_header.py
tests/v0x01/test_controller2switch/test_barrier_reply.py
tests/v0x01/test_controller2switch/test_barrier_request.py
tests/v0x01/test_controller2switch/test_features_reply.py
tests/v0x01/test_controller2switch/test_features_request.py
tests/v0x01/test_controller2switch/test_flow_mod.py
tests/v0x01/test_controller2switch/test_port_stats_request.py
tests/v0x01/test_foundation/test_basic_types.py
tests/v0x01/test_symmetric/test_echo_reply.py
tests/v0x01/test_symmetric/test_echo_request.py
tests/v0x01/test_symmetric/test_hello.py
tests/v0x02/test_common/test_flow_instruction.py

Fixing pep8 issues in tests

---

CONTRIBUTE.md

[doc] How to contribute with Sphinx docs

---

docs/toc/install.rst
requirements-dev.txt
requirements-docs.txt
requirements.txt
setup.cfg
setup.py
tests/v0x01/test_common/test_action.py
tests/v0x01/test_common/test_header.py
tests/v0x01/test_controller2switch/test_barrier_reply.py
tests/v0x01/test_controller2switch/test_barrier_request.py
tests/v0x01/test_controller2switch/test_features_reply.py
tests/v0x01/test_controller2switch/test_features_request.py
tests/v0x01/test_controller2switch/test_flow_mod.py
tests/v0x01/test_controller2switch/test_port_stats_request.py
tests/v0x01/test_foundation/test_basic_types.py
tests/v0x01/test_symmetric/test_echo_reply.py
tests/v0x01/test_symmetric/test_echo_request.py
tests/v0x01/test_symmetric/test_hello.py
tests/v0x02/test_common/test_flow_instruction.py

And also a few other changes in separate commits.

Issue #81 requirements

---

pyof/v0x01/common/utils.py
pyof/v0x01/foundation/base.py

Added two utilities functions to unpack messages

---

pyof/v0x01/foundation/base.py

Still need more work and some tests. related to: #103 
(For now the changes are sufficient to the controller, despite the need of improvements before closing the issue. But I would add this change right away)

First changes on basic_types operands.

---

pyof/v0x01/asynchronous/error_msg.py
pyof/v0x01/asynchronous/flow_removed.py
pyof/v0x01/asynchronous/packet_in.py
pyof/v0x01/asynchronous/port_status.py
pyof/v0x01/common/action.py
pyof/v0x01/common/flow_match.py
pyof/v0x01/common/header.py
pyof/v0x01/common/phy_port.py
pyof/v0x01/common/queue.py
pyof/v0x01/common/utils.py
pyof/v0x01/controller2switch/barrier_reply.py
pyof/v0x01/controller2switch/barrier_request.py
pyof/v0x01/controller2switch/common.py
pyof/v0x01/controller2switch/features_reply.py
pyof/v0x01/controller2switch/features_request.py
pyof/v0x01/controller2switch/flow_mod.py
pyof/v0x01/controller2switch/get_config_reply.py
pyof/v0x01/controller2switch/get_config_request.py
pyof/v0x01/controller2switch/packet_out.py
pyof/v0x01/controller2switch/port_mod.py
pyof/v0x01/controller2switch/queue_get_config_reply.py
pyof/v0x01/controller2switch/queue_get_config_request.py
pyof/v0x01/controller2switch/set_config.py
pyof/v0x01/controller2switch/stats_reply.py
pyof/v0x01/controller2switch/stats_request.py
pyof/v0x01/symmetric/echo_reply.py
pyof/v0x01/symmetric/echo_request.py
pyof/v0x01/symmetric/hello.py
pyof/v0x01/symmetric/vendor_header.py

FIX #126 
(Please, accept after the pull request #125 )

Adding __all__ attribute on every submodule.

---

pyof/v0x01/common/utils.py
pyof/v0x01/controller2switch/flow_mod.py
tests/rawdump.py
tests/testdump.py
tests/v0x01/test_controller2switch/test_barrier_reply.py

It does not close the issue yet, but provides a better way to test against raw dump files, both packing and unpacking. Documented in docstrings.

Issue #8 packing tests

---

pyof/v0x01/asynchronous/error_msg.py
pyof/v0x01/asynchronous/flow_removed.py
pyof/v0x01/asynchronous/packet_in.py
pyof/v0x01/asynchronous/port_status.py
pyof/v0x01/common/phy_port.py
pyof/v0x01/controller2switch/common.py

Mainly problems with enums starting at one instead of zero.

Fixing errors on enums numbering (values)

---

pyof/v0x01/common/action.py
pyof/v0x01/common/flow_match.py
pyof/v0x01/foundation/base.py
pyof/v0x01/foundation/basic_types.py
pyof/v0x01/symmetric/echo_reply.py

Close #144 
CHANGES: Fix doc syntax error

Fix doc syntax error

---

pyof/v0x01/asynchronous/error_msg.py

Removing commans from enums

---

pyof/foundation/basic_types.py
pyof/v0x01/common/flow_match.py

Changelog: Improvments on the default values of some v0x01 classes to allow a less verbose code.
Changelog:  - Match (FlowMatch)
There were also some minor improvements to make this changes work properly.
Related to #173

Improving some default values on v0x01

---

setup.py

setup.py test fails if doctest fails

---

pyof/v0x01/controller2switch/stats_request.py

Fix problems found while developing stats app.

Fix StatsRequest body type; add default values

---

pyof/v0x01/controller2switch/common.py

File was upgraded to v0x04 by mistake.

Revert v0x01 file in v0x01 folder

---

pyof/foundation/basic_types.py
pyof/foundation/network_types.py
pyof/v0x01/asynchronous/packet_in.py
pyof/v0x01/controller2switch/features_reply.py
pyof/v0x01/controller2switch/packet_out.py

CHANGELOG: Created a new network_types module.
CHANGELOG: Added LLDP and LLDP_TLV classes to network_types.

Improvements on networks classes/types

---

pyof/foundation/basic_types.py
pyof/v0x01/controller2switch/features_reply.py
tests/v0x01/test_controller2switch/test_features_reply.py

Fix DPID packing bug

---

pyof/foundation/basic_types.py
pyof/v0x01/common/flow_match.py
tests/test_foundation/test_basic_types.py

- Removed attribute wildcard_mask from IPAddress class
- Adding tests to netmask and max_prefix from IPAddress
- Fix #199

Remove attribute wildcard_mask from IPAddress

---

pyof/v0x01/common/action.py

Fix ActionHeader.unpack

---

docs/_static/custom.css

[doc] Fix white font on white background

---

pyof/foundation/base.py
pyof/foundation/basic_types.py
pyof/foundation/network_types.py
pyof/v0x01/asynchronous/packet_in.py
pyof/v0x01/common/action.py
pyof/v0x01/common/flow_match.py
pyof/v0x01/controller2switch/features_reply.py
pyof/v0x01/controller2switch/flow_mod.py
pyof/v0x01/controller2switch/packet_out.py
pyof/v0x01/controller2switch/stats_request.py
pyof/v0x04/controller2switch/get_async_reply.py
pyof/v0x04/controller2switch/packet_out.py
pyof/v0x04/controller2switch/set_async.py
requirements-dev.txt
setup.cfg
setup.py
tests/test_foundation/test_basic_types.py
tests/test_struct.py
tests/v0x02/test_common/__init__.py
tests/v0x04/test_controller2switch/test_packet_out.py

Add docstrings, fix PEP violations and add linting to build so there won't be docstrings missing again.

Docstrings #208

---

pyof/v0x01/common/header.py
tests/v0x01/test_common/test_header.py

Fix random xid bug

---

README.rst

Close #209 
- Emphasize no I/O in this library
- Section hierarchy reviewed 
- Fix unreachable links from GitHub's README
- Fix ignored *seealso* admonition by GitHub
- Fix code highlighting in GitHub

[doc] Improve first sections

---

README.rst
docs/AUTHORS.rst
docs/LICENSE.rst
docs/examples/index.rst
docs/get_involved.rst
docs/hacking.rst
docs/toc/introduction.rst

Fix docs headings according to the sphinx guidelines
Fix #178

Fix docs sphinx guidelines

---

docs/_templates/navbar.html

Adding bold to project name on DocCover bar.

---

docs/conf.py
docs/get_involved.rst
docs/getting_help.rst
docs/references.rst

Part of kytos/documentation#13

[doc] Update getting help and get involved

---

.travis.yml
requirements-dev.txt
tests/v0x01/test_asynchronous/test_error_msg.py

I forked this repo to test: https://coveralls.io/github/cemsbr/python-openflow

Add coveralls support

---

docs/.gitignore
pyof/foundation/network_types.py
requirements-dev.txt
setup.py
tests/test_foundation/test_network_types.py

Fix #238 with tests and other small improvements.

of_lldp bug

---

requirements-dev.txt
setup.py

Run `pip install -r requirements-dev.txt --upgrade` for a much faster linter.

Run unit tests first, before doctest and linter

---

pyof/v0x04/common/action.py

[1.3] Fix duplicate in ActionType

---

pyof/v0x04/common/action.py

[1.3] Fix missing attribute

---

pyof/v0x04/controller2switch/common.py

[1.3] Fix pad size and port_no size

---

pyof/v0x04/controller2switch/common.py
pyof/v0x04/controller2switch/group_mod.py
tests/v0x04/test_controller2switch/test_group_mod.py

Add group related OFPMP message bodies, for requests and replies. Minor refactoring changes.

Add group related classes

---

pyof/v0x04/controller2switch/common.py
tests/v0x04/test_controller2switch/test_meter_features.py

Adding MeterFeature class

---

pyof/v0x04/controller2switch/common.py

[1.3] Add class ofp_experimenter_header

---

README.rst

Fix python version in install command

---

pyof/v0x04/common/action.py

[1.3] Fix ofp_action_type class

---

pyof/v0x04/controller2switch/multipart_request.py

Fix MultipartRequest class header type

---

pyof/v0x04/controller2switch/get_config_reply.py

Fix header of GetConfigReply

---

pyof/v0x04/symmetric/hello.py

Add ofp_hello and related classes as described in 1.3.5 spec

Add Hello message

---

pyof/v0x04/common/utils.py

Updatting available_classes used to unpack messages from type
Fixing Pylama warnings

Updating new message from type v0x04

---

setup.py

Enable Openflow 1.3 in install script

---

.scrutinizer.yml

Changelog:
- Continuous Integration with:
- Code quality score
- Test coverage

Finish scrutinizer configuration

---

pyof/foundation/network_types.py

Add prefix to 'type' attributes

---

pyof/v0x01/common/queue.py
pyof/v0x04/common/queue.py
tests/v0x01/test_common/test_queue.py
tests/v0x01/test_controller2switch/test_queue_get_config_reply.py

Review 'property' and 'len' attributes

---

pyof/v0x01/symmetric/echo_reply.py
pyof/v0x01/symmetric/echo_request.py
requirements.txt

Adds binary data field for reply and request messages - also fix requirements.txt

---

pyof/v0x04/symmetric/experimenter.py

Add data field for symmetric/experimenter

---

setup.py

Adds classifiers to setup.py 

---

.scrutinizer.yml
requirements-dev.txt
setup.py
tox.ini

New tests:
- tox: all tests below + package installation
- python setup.py test: unit tests
- python setup.py coverage: test coverage
- python setup.py doctest: documentation test
- python setup.py lint: linter
kytos/kytos#317 for python-openflow

Use tox to also test package installation

---

pyof/foundation/base.py
pyof/foundation/basic_types.py
pyof/foundation/network_types.py
pyof/v0x01/common/flow_match.py
pyof/v0x01/controller2switch/barrier_reply.py
pyof/v0x01/controller2switch/barrier_request.py
pyof/v0x01/controller2switch/features_reply.py
pyof/v0x01/controller2switch/features_request.py
pyof/v0x01/controller2switch/get_config_request.py
pyof/v0x01/controller2switch/packet_out.py
pyof/v0x01/controller2switch/stats_reply.py
pyof/v0x01/symmetric/hello.py
pyof/v0x04/common/table_feature.py
pyof/v0x04/controller2switch/barrier_reply.py
pyof/v0x04/controller2switch/barrier_request.py
pyof/v0x04/controller2switch/common.py
pyof/v0x04/controller2switch/features_reply.py
pyof/v0x04/controller2switch/features_request.py
pyof/v0x04/controller2switch/get_async_request.py
pyof/v0x04/controller2switch/get_config_request.py
tests/test_class_inheritance/test_inheritance.py
tests/test_foundation/test_basic_types.py
tests/v0x01/test_common/test_flow_match.py
tests/v0x01/test_common/test_phy_port.py
tests/v0x01/test_common/test_queue.py

Fix linter errors after pylint update

---

pyof/foundation/base.py
pyof/v0x01/asynchronous/error_msg.py
pyof/v0x01/asynchronous/flow_removed.py
pyof/v0x01/asynchronous/packet_in.py
pyof/v0x01/asynchronous/port_status.py
pyof/v0x01/common/header.py
pyof/v0x01/common/phy_port.py
pyof/v0x01/common/queue.py
pyof/v0x01/controller2switch/common.py
pyof/v0x01/controller2switch/flow_mod.py
pyof/v0x01/controller2switch/packet_out.py
pyof/v0x04/asynchronous/error_msg.py
pyof/v0x04/asynchronous/flow_removed.py
pyof/v0x04/asynchronous/packet_in.py
pyof/v0x04/asynchronous/port_status.py
pyof/v0x04/common/action.py
pyof/v0x04/common/flow_instructions.py
pyof/v0x04/common/flow_match.py
pyof/v0x04/common/header.py
pyof/v0x04/common/port.py
pyof/v0x04/common/queue.py
pyof/v0x04/common/table_feature.py
pyof/v0x04/controller2switch/common.py
pyof/v0x04/controller2switch/flow_mod.py
pyof/v0x04/controller2switch/group_mod.py
pyof/v0x04/controller2switch/meter_mod.py
pyof/v0x04/controller2switch/multipart_request.py
pyof/v0x04/controller2switch/table_mod.py
pyof/v0x04/symmetric/hello.py

Fix #353 
Also small refactoring to validations, given that `isinstance(some_enum_attribute, int) == True` now.

Change integer Enums to IntEnum

---

CHANGELOG.rst

Renamed attributes added, according to review

Changes in changelog

---

pyof/v0x01/common/action.py

Add class for the Strip VLAN Action in OF 1.0.
Fix #399

Add ActionStripVlan class

---

.scrutinizer.yml
setup.cfg

Scrutinizer had a coverage bug fixed.

[minor] Fix Scrutinizer coverage

---

tests/v0x01/test_controller2switch/test_stats_reply.py
tests/v0x01/test_controller2switch/test_stats_request.py
tests/v0x04/test_controller2switch/test_multipart_reply.py
tests/v0x04/test_controller2switch/test_multipart_request.py

just small fixes in tests from a closed PR. 
https://github.com/erickvermot/python-openflow/commit/3ab02e12442ef3832b7ea5f7aa3606ab38672953
https://github.com/erickvermot/python-openflow/commit/c3cb36c34ecec5252d8f5446809d4628e65b9b62

Small tests fixes

---

pyof/foundation/base.py

related to https://github.com/kytos/python-openflow/issues/423

fix GenericType less_than operator

---

pyof/v0x04/common/action.py
pyof/v0x04/common/constants.py
pyof/v0x04/controller2switch/flow_mod.py

Add a missing constant from the spec;
Add a ,missing field in Flow Mods from the spec - (Instruction list is essential and it's commented in the document);
Refactor action.py for v0x04.

V0x04 fixes

---

pyof/foundation/basic_types.py
tests/test_foundation/test_basic_types.py

This PR was created to fix  kytos/python-openflow#420 .

Binarydata fixes

---

pyof/v0x01/controller2switch/packet_out.py
tests/v0x01/test_controller2switch/test_packet_out.py

- Update packetout validation
- Fix tests
- Fix #402

Fix PacketOut validation

---

pyof/v0x04/common/action.py
pyof/v0x04/common/flow_match.py
pyof/v0x04/controller2switch/common.py
pyof/v0x04/controller2switch/flow_mod.py
pyof/v0x04/controller2switch/multipart_request.py
pyof/v0x04/controller2switch/packet_out.py
pyof/v0x04/controller2switch/role_reply.py
pyof/v0x04/controller2switch/set_config.py
pyof/v0x04/controller2switch/table_mod.py
pyof/v0x04/symmetric/echo_reply.py
pyof/v0x04/symmetric/echo_request.py

Fix #451
Most common classes were reviewed, some still pending

Review default parameters for classes in v0x04

---

pyof/v0x04/common/action.py

Fix ActionSetField for v0x04

---

pyof/foundation/basic_types.py
tests/test_struct.py

Tests show 50% faster unpacking. Deepcopy is made manually
in basic types.

Improve performance

---

pyof/foundation/base.py
pyof/foundation/basic_types.py

Move __deepcopy__ code to parent class.

Refactoring

---

pyof/v0x04/controller2switch/multipart_reply.py

Fix FlowStatsReply Multipart Message missing field.
Future PRs will add tests for this struct - which is a complex case.

Fix flow stats reply

---

CHANGELOG.rst
pyof/v0x04/asynchronous/error_msg.py

[v0x04] Implement ErrorMsg unpack method.

---

pyof/v0x04/common/action.py

Add missing field for ActionSetField

---

pyof/v0x04/common/action.py

Fix #485
Now returns the length with the correct padding.

Fix Actions get_size method

---

pyof/v0x04/asynchronous/packet_in.py

Fix packet_in.in_port property to return an int

---

pyof/v0x04/controller2switch/common.py
pyof/v0x04/controller2switch/multipart_reply.py
pyof/v0x04/controller2switch/multipart_request.py

Rename multiparty to multipart

---

pyof/v0x01/controller2switch/common.py
pyof/v0x01/controller2switch/get_config_reply.py
pyof/v0x01/controller2switch/set_config.py
pyof/v0x01/controller2switch/stats_reply.py
pyof/v0x01/controller2switch/stats_request.py
pyof/v0x04/controller2switch/common.py
pyof/v0x04/controller2switch/get_config_reply.py
pyof/v0x04/controller2switch/multipart_reply.py
pyof/v0x04/controller2switch/multipart_request.py
pyof/v0x04/controller2switch/set_config.py
tests/v0x01/test_controller2switch/test_aggregate_stats_reply.py
tests/v0x01/test_controller2switch/test_aggregate_stats_request.py
tests/v0x01/test_controller2switch/test_desc_stats.py
tests/v0x01/test_controller2switch/test_flow_stats.py
tests/v0x01/test_controller2switch/test_flow_stats_request.py
tests/v0x01/test_controller2switch/test_get_config_reply.py
tests/v0x01/test_controller2switch/test_port_stats.py
tests/v0x01/test_controller2switch/test_port_stats_request.py
tests/v0x01/test_controller2switch/test_queue_stats.py
tests/v0x01/test_controller2switch/test_queue_stats_request.py
tests/v0x01/test_controller2switch/test_set_config.py
tests/v0x01/test_controller2switch/test_stats_reply.py
tests/v0x01/test_controller2switch/test_stats_request.py
tests/v0x01/test_controller2switch/test_table_stats.py
tests/v0x01/test_controller2switch/test_vendor_stats.py
tests/v0x04/test_controller2switch/test_multipart_reply.py
tests/v0x04/test_controller2switch/test_multipart_request.py

Please note: all NApps must be updated as well. A new PR for every NApp will be submitted.

Rename Enums to the default of the project

---

pyof/foundation/base.py
pyof/v0x01/common/header.py
pyof/v0x01/controller2switch/common.py
tests/raw_dump.py

New repr() methods for classes GenericMessage, Header, SwitchConfig,
and RawDump.

Easier debugging with repr's

---

CHANGELOG.rst
pyof/v0x01/asynchronous/error_msg.py
pyof/v0x04/asynchronous/error_msg.py

I forgot to push with -f on PR #533. This has the last requested changes. My bad!
@beraldoleal @hdiogenes

Added support for OpenFlow 1.3 OFP_ERROR codes with the get_class method

---

README.rst

Added develop mode install on README.rst

---

raw/README.rst

Openflow version was changed from 6633 to 6653.

Changed OpenFlow port to 6653 (#905)

---

CHANGELOG.rst

 Updated Changelog

---

tests/v0x04/test_controller2switch/test_flow_mod.py

Scrutinizer warned about some code style issues in PR #577, this fixes these issues.

Fix linter issues

---

requirements/dev.txt
setup.py

Had to temporarily turn linter errors into warnings
b/c of pylint upgrade.

Fix installation by upgrading requirements

---

pyof/foundation/base.py
pyof/foundation/basic_types.py
pyof/foundation/exceptions.py
pyof/foundation/network_types.py
pyof/v0x01/asynchronous/error_msg.py
pyof/v0x01/common/action.py
pyof/v0x01/controller2switch/packet_out.py
pyof/v0x01/controller2switch/stats_reply.py
pyof/v0x04/common/action.py
pyof/v0x04/common/flow_instructions.py
pyof/v0x04/common/flow_match.py
pyof/v0x04/controller2switch/common.py
pyof/v0x04/controller2switch/packet_out.py
pyof/v0x04/symmetric/hello.py
setup.py

There were some linter issues raised by new Pylint version. This commit fixes all of them.
Note: One issue has been disabled (comparison-with-callable), 
because it looks like a false positive.

Fix new linter issues

---

setup.py

Fix Coverage and Test not throwing errors when tests fail.

Fix Travis false positive message
